
CREATE PROCEDURE SP_FUNCIONARIOS_FAIXA_SALARIAL AS
DECLARE @VALOR_INICIAL NUMERIC(18,2), @VALOR_FINAL NUMERIC(18,2), @QTDE_MULHERES INT, @QTDE_HOMENS INT

CREATE TABLE #TEMP(
VALOR_INICIAL NUMERIC(18,2), VALOR_FINAL NUMERIC(18,2), QTDEMULHERES INT, QTDEHOMENS INT
)

SET @VALOR_INICIAL = 1;

WHILE @VALOR_INICIAL <= 27000
	BEGIN
	SET @VALOR_FINAL = @VALOR_INICIAL + 3000 -1

	SET @QTDE_MULHERES = (SELECT COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'F' AND SALARIO BETWEEN @VALOR_INICIAL AND @VALOR_FINAL);
	SET @QTDE_HOMENS = (SELECT COUNT(*) FROM FUNCIONARIO WHERE SEXO = 'M' AND SALARIO BETWEEN @VALOR_INICIAL AND @VALOR_FINAL);

	INSERT INTO #TEMP
	VALUES(@VALOR_INICIAL, @VALOR_FINAL, @QTDE_MULHERES, @QTDE_HOMENS)
	SET @VALOR_INICIAL = @VALOR_FINAL
	END

	SELECT * FROM #TEMP
	DROP TABLE #TEMP