--DIFERENCIANDO NUMEROS PARES E ÍMPARES


--ALTER PROCEDURE SP_PAR_IMPAR @INTERVALO INT AS

--DECLARE @INICIO INT = 1, @VL1 INT = 11, @RESTO INT

--IF EXISTS( SELECT * FROM SYSOBJECTS WHERE NAME = 'PAR')
--	BEGIN
--		DELETE PAR
--	END

--ELSE
--	BEGIN
--		CREATE TABLE PAR
--			(VL_NUMERO INT NULL,
--			DS_NUMERO VARCHAR(20) NULL)
--	END

--IF EXISTS( SELECT * FROM SYSOBJECTS WHERE NAME = 'IMPAR')
--	BEGIN
--		DELETE IMPAR
--	END
--ELSE
--	BEGIN
--	CREATE TABLE IMPAR
--		(VL_NUMERO INT NULL,
--		DS_NUMERO VARCHAR(20) NULL)
--	END

--WHILE @INICIO <= @INTERVALO
--	BEGIN
--		SET @RESTO  = @INICIO % 2
--		IF @RESTO = 0
--			BEGIN
--				INSERT INTO PAR VALUES (@INICIO, 'É UM NÚMERO PAR')
--			END
--		ELSE
--			BEGIN
--				INSERT INTO IMPAR VALUES (@INICIO, 'É UM NÚMERO IMPAR')

--			END
--		SET @INICIO = @INICIO + 1

		
--	END

--SELECT * FROM PAR		
--SELECT * FROM IMPAR

EXEC SP_PAR_IMPAR 15


--DIFERENCIANDO NUMEROS PARES E ÍMPARES TEMPORARIA


--CREATE PROCEDURE SP_PAR_IMPAR_TABELA_TEMPORARIA @INTERVALO INT AS

--DECLARE @INICIO INT = 1, @VL1 INT = 11, @RESTO INT

--CREATE TABLE #PAR_IMPAR
--			(VL_NUMERO INT NULL,
--			DS_NUMERO VARCHAR(20) NULL)

--WHILE @INICIO <= @INTERVALO
--	BEGIN
--		SET @RESTO  = @INICIO % 2
--		IF @RESTO = 0
--			BEGIN
--				INSERT INTO #PAR_IMPAR VALUES (@INICIO, 'É UM NÚMERO PAR')
--			END
--		ELSE
--			BEGIN
--				INSERT INTO #PAR_IMPAR VALUES (@INICIO, 'É UM NÚMERO IMPAR')

--			END
--		SET @INICIO = @INICIO + 1

		
--	END

--SELECT * FROM #PAR_IMPAR		

EXEC SP_PAR_IMPAR_TABELA_TEMPORARIA 15
