--CRIAÇÃO DE PROCEDURES
USE RH_UPPER_6319041
GO

--CREATE PROCEDURE SP_PESQUISA AS

--	SELECT CD_ESTADO, NM_ESTADO, DS_SIGLA  FROM ESTADO ORDER BY NM_ESTADO





EXEC SP_PESQUISA  --EXEC OU EXECUTE OU SOMENTE O NOME DA PROC
EXECUTE SP_PESQUISA
SP_PESQUISA

--Pesquisa com condição

--CREATE PROCEDURE SP_PESQUISA_SIGLA AS
--	SELECT CD_ESTADO, NM_ESTADO, DS_SIGLA FROM ESTADO WHERE DS_SIGLA = 'SP'

--USE [RH_UPPER_6319041]
--GO

--ALTER PROCEDURE [dbo].[SP_PESQUISA_SIGLA] @sigla varchar(2) AS
--	SELECT CD_ESTADO, NM_ESTADO, DS_SIGLA FROM ESTADO WHERE DS_SIGLA = @sigla
--GO

EXEC SP_PESQUISA_SIGLA 'BA'